# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("南航行李计算")
        Dialog.resize(596, 695)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.area = QtWidgets.QComboBox(Dialog)
        self.area.setObjectName("area")
        self.area.addItem("")
        self.area.addItem("")
        self.horizontalLayout.addWidget(self.area)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMinimumSize(QtCore.QSize(100, 0))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.region = QtWidgets.QComboBox(Dialog)
        self.region.setObjectName("region")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.region.addItem("")
        self.horizontalLayout_10.addWidget(self.region)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.passenger = QtWidgets.QComboBox(Dialog)
        self.passenger.setObjectName("passenger")
        self.passenger.addItem("")
        self.passenger.addItem("")
        self.passenger.addItem("")
        self.passenger.addItem("")
        self.passenger.addItem("")
        self.passenger.addItem("")
        self.passenger.addItem("")
        self.horizontalLayout_2.addWidget(self.passenger)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.space = QtWidgets.QComboBox(Dialog)
        self.space.setObjectName("space")
        self.space.addItem("")
        self.space.addItem("")
        self.space.addItem("")
        self.space.addItem("")
        self.horizontalLayout_3.addWidget(self.space)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.number = QtWidgets.QLineEdit(Dialog)
        self.number.setObjectName("number")
        self.horizontalLayout_4.addWidget(self.number)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.weight = QtWidgets.QLineEdit(Dialog)
        self.weight.setObjectName("weight")
        self.horizontalLayout_5.addWidget(self.weight)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.A = QtWidgets.QLineEdit(Dialog)
        self.A.setObjectName("A")
        self.horizontalLayout_6.addWidget(self.A)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.B = QtWidgets.QLineEdit(Dialog)
        self.B.setObjectName("B")
        self.horizontalLayout_7.addWidget(self.B)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.C = QtWidgets.QLineEdit(Dialog)
        self.C.setObjectName("C")
        self.horizontalLayout_8.addWidget(self.C)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.price = QtWidgets.QLineEdit(Dialog)
        self.price.setObjectName("price")
        self.horizontalLayout_9.addWidget(self.price)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.privilege = QtWidgets.QComboBox(Dialog)
        self.privilege.setObjectName("privilege")
        self.privilege.addItem("")
        self.privilege.addItem("")
        self.horizontalLayout_11.addWidget(self.privilege)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_12.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.result = QtWidgets.QTextEdit(Dialog)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "飞行范围："))
        self.area.setItemText(0, _translate("Dialog", "国内"))
        self.area.setItemText(1, _translate("Dialog", "涉及国外"))
        self.label_10.setText(_translate("Dialog", "区域："))
        self.region.setItemText(0, _translate("Dialog", "日本、美洲、澳新、俄罗斯、迪拜的航程，以及新加坡始发与中国大陆间的航程\n"
                                                        ""))
        self.region.setItemText(1, _translate("Dialog", "中西亚的航程 \n"
                                                        ""))
        self.region.setItemText(2, _translate("Dialog", "内罗毕的航程"))
        self.region.setItemText(3, _translate("Dialog", "除日本、美洲、澳新、俄罗斯、迪拜、内罗毕、中西亚以外的国际/地区航程"))
        self.region.setItemText(4, _translate("Dialog", "韩国始发与中国间的航程"))
        self.label_2.setText(_translate("Dialog", "游客类型："))
        self.passenger.setItemText(0, _translate("Dialog", "成年人"))
        self.passenger.setItemText(1, _translate("Dialog", "儿童"))
        self.passenger.setItemText(2, _translate("Dialog", "占座婴儿"))
        self.passenger.setItemText(3, _translate("Dialog", "不占座婴儿"))
        self.passenger.setItemText(4, _translate("Dialog", "南航明珠金卡会员/天合联盟超级精英"))
        self.passenger.setItemText(5, _translate("Dialog", "南航明珠银卡会员/天合联盟精英"))
        self.passenger.setItemText(6, _translate("Dialog", "留学生/劳务/海员"))
        self.label_3.setText(_translate("Dialog", "舱位："))
        self.space.setItemText(0, _translate("Dialog", "头等舱"))
        self.space.setItemText(1, _translate("Dialog", "公务舱"))
        self.space.setItemText(2, _translate("Dialog", "明珠经济舱"))
        self.space.setItemText(3, _translate("Dialog", "经济舱"))
        self.label_8.setText(_translate("Dialog", "行李件数："))
        self.label_4.setText(_translate("Dialog", "重量列表："))
        self.label_5.setText(_translate("Dialog", "长度列表："))
        self.label_6.setText(_translate("Dialog", "宽度列表："))
        self.label_7.setText(_translate("Dialog", "高度列表："))
        self.label_9.setText(_translate("Dialog", "票价："))
        self.label_11.setText(_translate("Dialog", "特别旅客选择："))
        self.privilege.setItemText(0, _translate("Dialog", "计重制"))
        self.privilege.setItemText(1, _translate("Dialog", "计件制"))
        self.label_12.setText(_translate("Dialog", "结果："))
        self.pushButton.setText(_translate("Dialog", "计算"))
